# Generated by Django 6.0.1 on 2026-02-10 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_id", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("travelers", models.IntegerField()),
                ("date", models.DateField()),
                ("budget", models.CharField(max_length=50)),
                ("status", models.CharField(default="Pending", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="TravelBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                (
                    "travelers",
                    models.CharField(
                        choices=[
                            ("1", "1 Traveler (Solo)"),
                            ("2", "2 Travelers (Couple)"),
                            ("3", "3 Travelers"),
                            ("4", "4 Travelers"),
                            ("5", "5 Travelers"),
                            ("6", "6 Travelers"),
                            ("7", "7 Travelers"),
                            ("8", "8 Travelers"),
                            ("9-15", "9-15 Travelers (Group)"),
                            ("16+", "16+ Travelers (Large Group)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "travel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solo", "Solo Travel"),
                            ("family", "Family Travel"),
                            ("couple", "Couple Getaway"),
                            ("group", "Group Adventure"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "date_flexibility",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed dates - cannot change"),
                            ("flexible-few-days", "Flexible ± 2-3 days"),
                            ("flexible-week", "Flexible ± 1 week"),
                            ("flexible-month", "Flexible - planning months in advance"),
                        ],
                        default="flexible-month",
                        max_length=30,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=7,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(21),
                        ],
                    ),
                ),
                ("activities", models.TextField(blank=True, default="[]")),
                (
                    "accommodation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("luxury", "5-Star Luxury"),
                            ("boutique", "Boutique Lodges"),
                            ("mid-range", "Mid-Range Hotels"),
                            ("budget", "Budget-Friendly"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.IntegerField(
                        default=5000,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(15000),
                        ],
                    ),
                ),
                ("special_requests", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="core_travel_email_daadc6_idx"),
                    models.Index(
                        fields=["status"], name="core_travel_status_d64957_idx"
                    ),
                ],
            },
        ),
    ]
