# Generated by Django 6.0.1 on 2026-06-22 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_travelbooking_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelbooking",
            name="budget",
            field=models.IntegerField(
                default=5000,
                validators=[
                    django.core.validators.MinValueValidator(500),
                    django.core.validators.MaxValueValidator(50000),
                ],
            ),
        ),
    ]
